[project]
name = "openai2ollama"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.125.0",
    "httpx>=0.28.1",
    "ollama>=0.6.1",
    "openai>=2.13.0",
    "uvicorn>=0.38.0",
]
